# Generated by Django 6.0.6 on 2026-06-08 23:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ScamReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fingerprint', models.CharField(db_index=True, max_length=64, unique=True)),
                ('fraud_category', models.CharField(choices=[('PHISHING', 'Phishing'), ('PRIZE_FRAUD', 'Prize Fraud'), ('IMPERSONATION', 'Impersonation'), ('INVESTMENT_FRAUD', 'Investment Fraud'), ('ROMANCE_SCAM', 'Romance Scam'), ('NONE', 'None')], max_length=20)),
                ('threat_level', models.CharField(choices=[('LOW', 'Low'), ('MEDIUM', 'Medium'), ('HIGH', 'High'), ('CRITICAL', 'Critical')], max_length=10)),
                ('flagged_phrases', models.JSONField(default=list)),
                ('explanation', models.TextField()),
                ('recommended_action', models.TextField()),
                ('report_count', models.PositiveIntegerField(default=1)),
                ('source', models.CharField(choices=[('TEXT', 'Text'), ('IMAGE', 'Image')], max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='ThreatActor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contact_type', models.CharField(choices=[('PHONE', 'Phone'), ('WHATSAPP', 'WhatsApp'), ('BANK_ACCOUNT', 'Bank Account'), ('URL', 'URL'), ('EMAIL', 'Email'), ('ORG_NAME', 'Organisation Name')], max_length=20)),
                ('contact_value', models.CharField(db_index=True, max_length=255)),
                ('label', models.CharField(max_length=255)),
                ('report_count', models.PositiveIntegerField(default=1)),
                ('fraud_categories', models.JSONField(default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'unique_together': {('contact_type', 'contact_value')},
            },
        ),
    ]
