# Generated by Django 6.0.6 on 2026-06-10 10:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('detection', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AuthorityReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('agency', models.CharField(choices=[('EFCC', 'EFCC'), ('NITDA', 'NITDA'), ('CBN', 'CBN'), ('NPF', 'Nigeria Police Force')], max_length=20)),
                ('reporter_note', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('scam_report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='authority_reports', to='detection.scamreport')),
            ],
        ),
    ]
